
on: push

name: Integration 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
            go build 
      - name: Test
        run: |
            go test 
            echo "Tested"
          
        
     