
on: push

name: Integration 

jobs:
  build:

    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go-version: 
          - "1.18"
          - "1.17"
          - "1.16"
       

      
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
            go build 
      - name: Test
        run: |
            go test 
            echo "Tested"
          
        
     